# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: (moreâ€¦)
fancybox: true

# Miscellaneous
google_analytics: UA-70909383-1
favicon: /favicon.png

# Social
twitter: ikkou